apiVersion: v1
kind: Service
metadata:
  name: { { include "food-order-bd.fullname" . } }
  labels: { { - include "food-order-bd.labels" . | nindent 4 } }
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: 8008
      protocol: TCP
      name: http
  selector: { { - include "food-order-bd.selectorLabels" . | nindent 4 } }
